### ISSUE TITLE
Oops Error : 400 - Invalid redirect_uri

### ISSUE THREAD

**Issue by AlABarazi** [Autodesk-Forge/learn.forge.viewhubmodels#15]
What is the cause of this ? 

![Aug-02-2019 23-06-50](https://user-images.githubusercontent.com/7549404/62395945-6a907380-b57a-11e9-8512-2995b2f953b7.gif)

**Comment by augustogoncalves** [comment]
Please make sure to use the same callback URL on both Forge portal and on your app. See this section of the tutorial: http://learnforge.autodesk.io/#/account/?id=create-an-app

**Comment by AlABarazi** [comment]
Thanks ! It is working now but the viewer is not showing the file when I click on it.

![Aug-04-2019 12-12-18](https://user-images.githubusercontent.com/7549404/62421860-8e0a0a00-b6b1-11e9-9062-e3981cb38811.gif)

**Comment by augustogoncalves** [comment]
Please upload your own files to your hub, those sample files are just for demonstration of the product (not a good example of API usage).

**Comment by AlABarazi** [comment]
I uploaded my own IFC file and it didn't work. I am still having the same problem

**Comment by augustogoncalves** [comment]
can you view them on A360/BIM360Team/FusionTeam (whichever you're using)? Just make sure to open it at least once there so it is translated. 

if the problem persists, try opening the developer tools on your browser and check the console for any error message.

**Comment by AlABarazi** [comment]
> can you view them on A360/BIM360Team/FusionTeam (whichever you're using)? Just make sure to open it at least once there so it is translated.

This solved the problem. Thanks!

**Comment by jmcouffin** [comment]
if on Heroku:
![image](https://user-images.githubusercontent.com/7872003/133047227-f0dc1700-079f-47bf-9ee5-e632ccc7a5eb.png)
